### ISSUE TITLE
Is it necessary to provide only the space group number for the calculation of the magnetic system?

### ISSUE THREAD

**Issue by xuey06** [zjwang11/irvsp#5]
Dear Wang,

To calculate the representations for the bands of a **magnetic** system, how to set the command for irvsp_v2? 
Can I still use "irvsp -sg sgnuber > repname.dat", or to use the magnetic space group number (BNS number)?

Thanks

**Comment by zjwang11** [comment]
Please follow the steps on this website:
http://tm.iphy.ac.cn/TopMat_1651msg.html

**Comment by xuey06** [comment]
Thank you!

> Please follow the steps on this website: http://tm.iphy.ac.cn/TopMat_1651msg.html
